deployment:
  tasks:
    - name: Instalar dependencias
      command: npm install

    - name: Construir la aplicación
      command: npm run build

    - name: Copiar archivos al directorio público
      command: cp -R build/* public_html/
